### ISSUE TITLE
need Gadfly-based plots

### ISSUE THREAD

**Issue by cecileane** [cecileane/PhyloPlots.jl#1]
For now, Gadfly-based functions have been commented out. Using both Gadfly and RCall causes compilation errors. Things run & test fine if using Gadfly only, or using RCall only (current choice). Using both works if we don't use PhyloNetworks also... These issues were with using:

    - Gadfly                        0.6.5+ commit c778af59f9, tagged v0.7.0
    - RCall                         0.10.3
    - PhyloNetworks                 0.6.0+ commit 88b8ac5107

warning messages when using RCall (with or without Gadfly): many messages this one, with "R_NaString" replaced by various things from RCall

    WARNING: eval from module Const to PhyloPlots:    
    Expr(:block, Expr(:line, 73, Symbol("/Users/ane/.julia/v0.6/RCall/src/Const.jl"))::Any, Expr(:., :NaString, Expr(:quote, :p)::Any)::Any = Expr(:call, :unsafe_load, Expr(:call, :cglobal, "R_NaString", Expr(:call, :typeof, Expr(:., :NaString, Expr(:quote, :p)::Any)::Any)::Any)::Any)::Any)::Any
      ** incremental compilation may be broken for this module **

error messages when using all 3 packages, RCall, Gadfly, PhyloNetworks (the stacktrace looks useless):

    ERROR: LoadError: MethodError: no method matching convert(::Type{AssertionError}, ::String)
    Closest candidates are:
      convert(::Type{Any}, ::ANY) at essentials.jl:28
      convert(::Type{T}, ::T) where T at essentials.jl:29

and final error:

    MethodError(Core.Inference.convert, (AssertionError, "invalid age range update"), 0x0000000000000ac6)

**Comment by nalimilan** [comment]
Looks like https://github.com/JuliaLang/julia/issues/23200?

**Comment by cecileane** [comment]
or more like JuliaLang/julia#21653 . The error (and stacktrace) is really similar to what @mauro3 showed, and it has to do with using multiple packages within the same module (RCall, Gadfly, PhyloNetworks in my case), like others have mentioned. I got the error above with julia v0.6.2, and don't get it with julia v0.6.1 .
