### ISSUE TITLE
the progress bar keeps getting stuck

### ISSUE THREAD

**Issue by Armeniacavulgaris** [cecileane/PhyloPlots.jl#22]
When installing PhyloPlots using the Julia package, the system does not report an error, but the progress bar keeps getting stuck and I don't know what the problem is.
![image](https://user-images.githubusercontent.com/108312716/220818608-a1665e36-10ab-4b28-bc29-9f8bb02ee4d9.png)

**Comment by cecileane** [comment]
The pre-compilation step took a while for me too, but it completed successfully..

**Comment by Armeniacavulgaris** [comment]
> The pre-compilation step took a while for me too, but it completed successfully..
The pre-compilation has been going on for three days and I have tried to fix the slow download by other means but each time it appears to stop in the middle of downloading PhyloPlots, so how long does it take to download PhyloPlots?
![image](https://user-images.githubusercontent.com/108312716/221181861-3800f1b0-425f-47fb-bd8b-e04a7ee03737.png)
![image](https://user-images.githubusercontent.com/108312716/221181934-05ecca7a-c269-49bc-81eb-14fa709540f9.png)

**Comment by cecileane** [comment]
A slow download would be caused by your internet connection, so I cannot help here.
